apiVersion: v1
kind: Pod
metadata:
  name: moviesearchnodejs.example.com
  labels:
    app: moviesearchnodejs
spec:
  containers:
  - name: moviesearchnodejs
    image: deepanshululla/movie_search_nodejs
    ports:
    - name: nodejs-port
      containerPort: 3000
